#!/bin/bash
set -eu

source cmd/config
COMMAND="${ELM_DOC_PREVIEW} --no-browser"
COMMENT="Starting offline documentation at http://localhost:8000/\n    With this utility you can browse the Elm documentation\n    also without a connection to internet"
singleCommand "${COMMAND}" "${COMMENT}"