#!/bin/bash
set -eu

source cmd/config
createIndexHtml
COMMAND="${ELM_GO} src/Main.elm --dir=docs --pushstate --start-page=index.html --hot --port=4200 --path-to-elm=${ELM} -- --output=docs/js/elm.js --debug"
COMMENT="Starting the development environment"
singleCommand "${COMMAND}" "${COMMENT}"