#!/bin/bash
set -eu

source cmd/config
COMMAND="${ELM_JSON} upgrade"
COMMENT="Upgrading the Elm dependencies"
singleCommand "${COMMAND}" "${COMMENT}"

printf "\n\n"

COMMAND="cd review; ../${ELM_JSON} upgrade"
COMMENT="Upgrading the Elm dependencies in the review folder"
singleCommand "${COMMAND}" "${COMMENT}"